image:
- Visual Studio 2017

hosts:
  api.nuget.org: 93.184.221.200

before_build:
- dotnet restore

test_script:
- dotnet test .\Bonus.Metadata.Test\Bonus.Metadata.Test.csproj
- dotnet test .\Bonus.Metadata.Sample\Bonus.Metadata.Sample.csproj

cache:
- '%USERPROFILE%\.nuget\packages'